name:                mal-api
version:             0.1.0.0
github:              "emekoi/mal-api"
license:             MIT
author:              "Emeka Nkurumeh"
maintainer:          "emekankurumeh@outlook.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/emekoi/mal-api#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.4.0
- text-manipulate >= 0.2.0.1
- time >= 1.1.0
- req >= 3.2.0
- aeson >= 1.4.7.1
- aeson-pretty >= 0.8.8
- bytestring >= 0.10.10

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - DuplicateRecordFields

library:
  source-dirs: src
  ghc-options:
    - '-pgml clang'
    - '-optc-pipe'
  ld-options: '-fuse-ld=lld'

executables:
  mal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - '-pgml clang'
    - '-optc-pipe'
    ld-options: '-fuse-ld=lld'
    dependencies:
    - mal-api

tests:
  mal-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mal-api
